services:
  - type: web
    name: livechat
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/livechat-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
